services:
  server:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 9000
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
    ports:
      - 9000:9000
    depends_on:
      - db

  client:
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: